version: 2.1
orbs:
  node: circleci/node@4.3.0
jobs:
  build_and_test:
    docker:
      - image: 'cimg/node:lts'
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "React-Dojo/netflix_clone_react/package-lock.json" }}
      - run: 
          name: install
          working_directory: React-Dojo/netflix_clone_react
          command: npm i
      - save_cache:
          key: v1-deps-{{ checksum "React-Dojo/netflix_clone_react/package-lock.json" }}
          paths:
            - React-Dojo/netflix_clone_react//node_modules
      - run:
          name: test
          working_directory: React-Dojo/netflix_clone_react
          command: npm run test
workflows:
  build_and_test:
    jobs:
      - build_and_test